/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.twitterApplication.dto;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class TweetKafkaDTO extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 845602087508804310L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"TweetKafkaDTO\",\"namespace\":\"com.twitterApplication.dto\",\"fields\":[{\"name\":\"userId\",\"type\":\"long\"},{\"name\":\"content\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<TweetKafkaDTO> ENCODER =
      new BinaryMessageEncoder<TweetKafkaDTO>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<TweetKafkaDTO> DECODER =
      new BinaryMessageDecoder<TweetKafkaDTO>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<TweetKafkaDTO> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<TweetKafkaDTO> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<TweetKafkaDTO>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this TweetKafkaDTO to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a TweetKafkaDTO from a ByteBuffer. */
  public static TweetKafkaDTO fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public long userId;
  @Deprecated public java.lang.CharSequence content;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public TweetKafkaDTO() {}

  /**
   * All-args constructor.
   * @param userId The new value for userId
   * @param content The new value for content
   */
  public TweetKafkaDTO(java.lang.Long userId, java.lang.CharSequence content) {
    this.userId = userId;
    this.content = content;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return userId;
    case 1: return content;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: userId = (java.lang.Long)value$; break;
    case 1: content = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'userId' field.
   * @return The value of the 'userId' field.
   */
  public java.lang.Long getUserId() {
    return userId;
  }

  /**
   * Sets the value of the 'userId' field.
   * @param value the value to set.
   */
  public void setUserId(java.lang.Long value) {
    this.userId = value;
  }

  /**
   * Gets the value of the 'content' field.
   * @return The value of the 'content' field.
   */
  public java.lang.CharSequence getContent() {
    return content;
  }

  /**
   * Sets the value of the 'content' field.
   * @param value the value to set.
   */
  public void setContent(java.lang.CharSequence value) {
    this.content = value;
  }

  /**
   * Creates a new TweetKafkaDTO RecordBuilder.
   * @return A new TweetKafkaDTO RecordBuilder
   */
  public static com.twitterApplication.dto.TweetKafkaDTO.Builder newBuilder() {
    return new com.twitterApplication.dto.TweetKafkaDTO.Builder();
  }

  /**
   * Creates a new TweetKafkaDTO RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new TweetKafkaDTO RecordBuilder
   */
  public static com.twitterApplication.dto.TweetKafkaDTO.Builder newBuilder(com.twitterApplication.dto.TweetKafkaDTO.Builder other) {
    return new com.twitterApplication.dto.TweetKafkaDTO.Builder(other);
  }

  /**
   * Creates a new TweetKafkaDTO RecordBuilder by copying an existing TweetKafkaDTO instance.
   * @param other The existing instance to copy.
   * @return A new TweetKafkaDTO RecordBuilder
   */
  public static com.twitterApplication.dto.TweetKafkaDTO.Builder newBuilder(com.twitterApplication.dto.TweetKafkaDTO other) {
    return new com.twitterApplication.dto.TweetKafkaDTO.Builder(other);
  }

  /**
   * RecordBuilder for TweetKafkaDTO instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<TweetKafkaDTO>
    implements org.apache.avro.data.RecordBuilder<TweetKafkaDTO> {

    private long userId;
    private java.lang.CharSequence content;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.twitterApplication.dto.TweetKafkaDTO.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.userId)) {
        this.userId = data().deepCopy(fields()[0].schema(), other.userId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.content)) {
        this.content = data().deepCopy(fields()[1].schema(), other.content);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing TweetKafkaDTO instance
     * @param other The existing instance to copy.
     */
    private Builder(com.twitterApplication.dto.TweetKafkaDTO other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.userId)) {
        this.userId = data().deepCopy(fields()[0].schema(), other.userId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.content)) {
        this.content = data().deepCopy(fields()[1].schema(), other.content);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'userId' field.
      * @return The value.
      */
    public java.lang.Long getUserId() {
      return userId;
    }

    /**
      * Sets the value of the 'userId' field.
      * @param value The value of 'userId'.
      * @return This builder.
      */
    public com.twitterApplication.dto.TweetKafkaDTO.Builder setUserId(long value) {
      validate(fields()[0], value);
      this.userId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'userId' field has been set.
      * @return True if the 'userId' field has been set, false otherwise.
      */
    public boolean hasUserId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'userId' field.
      * @return This builder.
      */
    public com.twitterApplication.dto.TweetKafkaDTO.Builder clearUserId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'content' field.
      * @return The value.
      */
    public java.lang.CharSequence getContent() {
      return content;
    }

    /**
      * Sets the value of the 'content' field.
      * @param value The value of 'content'.
      * @return This builder.
      */
    public com.twitterApplication.dto.TweetKafkaDTO.Builder setContent(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.content = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'content' field has been set.
      * @return True if the 'content' field has been set, false otherwise.
      */
    public boolean hasContent() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'content' field.
      * @return This builder.
      */
    public com.twitterApplication.dto.TweetKafkaDTO.Builder clearContent() {
      content = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public TweetKafkaDTO build() {
      try {
        TweetKafkaDTO record = new TweetKafkaDTO();
        record.userId = fieldSetFlags()[0] ? this.userId : (java.lang.Long) defaultValue(fields()[0]);
        record.content = fieldSetFlags()[1] ? this.content : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<TweetKafkaDTO>
    WRITER$ = (org.apache.avro.io.DatumWriter<TweetKafkaDTO>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<TweetKafkaDTO>
    READER$ = (org.apache.avro.io.DatumReader<TweetKafkaDTO>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
